# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches:
      - master
#   create:
#     tags:
#      - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm run predev
          npm run build
      - name: Test
        run: npm test
      - name: Docker login
        run: docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: LS
        run: ls -la
      - name: Build
        run: docker build -f Dockerfile -t docker.pkg.github.com/rollun-com/swagger-editor/swagger-editor:latest .
      - name: Push
        run: docker push docker.pkg.github.com/rollun-com/swagger-editor/swagger-editor:latest
      - name: Deploy D2C
        run: wget ${{ secrets.D2C_DEPLOY_WEBHOOK }}
